name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dashboard_ssd_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MIX_ENV: test
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dashboard_ssd_test
      PGHOST: localhost
      PGPORT: 5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.1'
          elixir-version: '1.17.3'

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Dialyzer PLTs
        env:
          MIX_ENV: dev
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Dialyzer
        env:
          MIX_ENV: dev
        run: mix dialyzer --format short

      - name: Prepare DB
        run: |
          mix ecto.create
          mix ecto.migrate

      - name: Tests
        run: mix test

      - name: Docs
        env:
          MIX_ENV: dev
        run: mix docs
